author: HASHBANG Productions
author_url: https://hbang.github.io/
github_url: https://github.com/hbang/Alderis
root_url: https://hbang.github.io/Alderis/
dash_url: https://hbang.github.io/Alderis/docsets/Alderis.xml
documentation: info/*.md
hide_documentation_coverage: true

custom_categories:
  - name: "Guides"
    children:
      - "Preference Bundles"

  - name: "Color Picker"
    children:
      - ColorPickerViewController
      - ColorPickerConfiguration
      - ColorPickerDelegate
      - ColorPickerTab
  
  - name: "UI Components"
    children:
      - ColorWell

  - name: "Deprecated"
    children:
      - ColorPickerCircleView
